### ISSUE TITLE
need help on create/update wiremock extension

### ISSUE THREAD

**Issue by srivi1225** [ebuzzing/wiremock-json-extractor#24]
Hi,

I am mocking a soap service and generating the dynamic xml response using body-transformer after that i am using wiremock postserveaction with webhook to call another service.to full fill my requirement i have the below challenges.

1. the webhook request should be dynamic one-- it should read the url from the request xml using xpath
2. the response generate by body-transformer should be send as the request body.

Can you please guide me in the right path to update the webhook extension.

Thanks,
Sri

**Comment by AlixBa** [comment]
Hello Sri,
You're at the wrong place here.

The original repository is : https://github.com/tomakehurst/wiremock
But this question belongs to the official mailing list :)
